trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: Traxpense-Variable-Groups

steps:
  - task: Cake@0
    inputs:
      script: 'build.cake'
      target: 'PushToNuget'
      verbosity: 'Verbose'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |       
        Get-ChildItem -Path ./artifacts/mvcapp
      errorActionPreference: 'continue'
      pwsh: true
